Repository Likelion-at-SMWU-13th/Tumbloom-FE, pull requests merged in 2025-08, with the labels that each got.

#2 Feat/#1/initial setting
  .gitignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  src/pages/Home/HomePage.jsx
  src/router.jsx
  vite.config.js
Labels: ⚙️ Setting, 🦁 승채

#19 Feat/#18/메인페이지 필터 탭 연결, 모달창 연결
  src/assets/images/preference-bg.svg
  src/components/Home/CafeCarousel.jsx
  src/components/Home/CafeRecommend.jsx
  src/components/Home/FilterTap.jsx
  src/components/Home/MatrixBar.jsx
  src/components/Home/PreferenceCard.jsx
  src/components/Home/TumblerInfo.jsx
  src/components/Home/styled.js
  src/pages/HomePage.jsx
  src/router.jsx
Labels: 🦁 채빈, ✨ Feature

#23 21 feat 스탬프 적립하기 페이지
  src/assets/images/get-stamp-cafe.png
  src/assets/images/get-stamp.svg
  src/assets/images/stamp-effect-bg.png
  src/assets/images/stamp-effect-bg.svg
  src/components/getStamp/GetStamp.Styled.js
  src/components/getStamp/GetStamp.jsx
  src/components/getStamp/StampAccess.Styled.js
  src/components/getStamp/StampAccess.jsx
  src/components/login/Login.jsx
  src/router.jsx
Labels: 🦁 승채, ✨ Feature

#33 Feat/#32/쿠폰 상세 페이지-사용하기 페이지 구현
  src/assets/icons/check.svg
  src/assets/icons/warning.svg
  src/components/CouponUse/CouponUse.jsx
  src/components/CouponUse/styled.js
  src/components/common/NoticeModal.Styled.js
  src/components/common/NoticeModal.jsx
  src/pages/CouponDetailPage.jsx
  src/router.jsx
Labels: 🦁 채빈, ✨ Feature

#40 Feat/#38/level modal
  src/assets/icons/close-gray.svg
  src/components/Home/styled.js
  src/components/MyPage/LevelModal.jsx
  src/components/MyPage/ProfileContent.jsx
  src/components/MyPage/styled.js
  src/pages/MyPage.jsx
Labels: 🦁 채빈, ✨ Feature

#43 Feat/#41/카페 취향 선택하기 페이지 구현
  src/assets/icons/animal-green.svg
  src/assets/icons/animal.svg
  src/assets/icons/atmosphere-green.svg
  src/assets/icons/atmosphere.svg
  src/assets/icons/brand-green.svg
  src/assets/icons/brand.svg
  src/assets/icons/brunch-green.svg
  src/assets/icons/brunch.svg
  src/assets/icons/cake-green.svg
  src/assets/icons/cake.svg
  src/assets/icons/decaf-green.svg
  src/assets/icons/decaf.svg
  src/assets/icons/eco-green.svg
  src/assets/icons/eco.svg
  src/assets/icons/event-green.svg
  src/assets/icons/event.svg
  src/assets/icons/hot-green.svg
  src/assets/icons/hot.svg
  src/assets/icons/meet-green.svg
  src/assets/icons/meet.svg
  src/assets/icons/season-menu-green.svg
  src/assets/icons/season-menu.svg
  src/assets/icons/special-tea-green.svg
  src/assets/icons/special-tea.svg
  src/assets/icons/study-green.svg
  src/assets/icons/study.svg
  src/assets/icons/sun-green.svg
  src/assets/icons/sun.svg
  src/assets/icons/unique-green.svg
  src/assets/icons/unique.svg
  src/components/Preference/Button.jsx
  src/components/Preference/ChoosePreference.jsx
  src/components/Preference/styled.js
  src/components/common/NoticeModal.Styled.js
  src/pages/Preference.jsx
  src/router.jsx
Labels: 🦁 채빈, ✨ Feature

#47 feat/#45/즐겨찾는 카페 페이지 구현 완료
  src/components/FavoriteCafeList/FavoriteCafeList.jsx
  src/components/FavoriteCafeList/styled.js
  src/pages/FavoriteCafe.jsx
  src/router.jsx
Labels: 🦁 채빈, ✨ Feature

#49 chore/#48/상태바 연결 및 마이페이지 데이터 props 연결
  src/components/MyPage/ProfileContent.jsx
  src/components/MyPage/ProfileInfo.jsx
  src/components/MyPage/StateBar.jsx
  src/components/MyPage/styled.js
  src/pages/MyPage.jsx
Labels: 🦁 채빈, ✨ Feature

#62 Feat/#59/마이페이지 데이터 연동
  src/components/Coupon/MyCoupon.jsx
  src/components/FavoriteCafeList/FavoriteCafeList.jsx
  src/components/Home/MatrixBar.jsx
  src/components/MyPage/MyPageBox.jsx
  src/components/MyPage/ProfileContent.jsx
  src/components/MyPage/ProfileInfo.jsx
  src/components/MyPage/StateBar.jsx
  src/components/MyPage/styled.js
  src/components/Preference/ChoosePreference.jsx
  src/components/ProfileShare/ProfileCard.jsx
  src/components/ProfileShare/ProfileShareBox.jsx
  src/components/common/CafeListCard.Styled.js
  src/pages/Coupon.jsx
  src/pages/FavoriteCafe.jsx
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileShare.jsx
Labels: 🦁 채빈, 📬 API

#69 api/#68/즐겨찾는 카페 페이지 연동 완료 및 목데이터 삭제
  src/components/Coupon/MyCoupon.jsx
  src/components/FavoriteCafeList/FavoriteCafeList.jsx
Labels: 🦁 채빈, 📬 API

#71 64 feat 새싹 클릭 시 나타나는 카페 카드 구현
  src/components/Map/KakaoMap.jsx
  src/components/Map/Map.jsx
  src/components/Map/MapCafeCard.jsx
Labels: 🦁 승채, ✨ Feature

#78 Feat/#74/로그인 실패 안내 텍스트 띄우기
  src/components/login/Login.jsx
Labels: 🦁 승채, 🎨 Design, 🔨 Refactor

#100 Api/#99/직원 확인코드 스탬프 적립 연동
  src/components/CafeInfo/CafeDetail.jsx
  src/components/getStamp/GetStamp.Styled.js
  src/components/getStamp/GetStamp.jsx
  src/components/getStamp/StampAccess.jsx
Labels: 🦁 승채, 📬 API

#105 Api/#101/지도 검색 연동 및 레이아웃 조정
  src/components/Map/KakaoMap.jsx
  src/components/Map/Map.jsx
  src/components/Map/SearchBox.jsx
  src/components/getStamp/QrScan.jsx
Labels: 🦁 승채, 📬 API

#113 Chore/#112/환경변수로 API 주소 관리 수정 완료
  src/components/CafeInfo/CafeDetail.jsx
  src/components/CafeList/CafeList.jsx
  src/components/Coupon/CouponChange.jsx
  src/components/Coupon/MyCoupon.jsx
  src/components/FavoriteCafeList/FavoriteCafeList.jsx
  src/components/Map/KakaoMap.jsx
  src/components/Map/MapCafeCard.jsx
  src/components/Preference/ChoosePreference.jsx
  src/components/getStamp/StampAccess.jsx
  src/components/login/Login.jsx
  src/components/signup/SignUp.jsx
  src/pages/CouponDetailPage.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileShare.jsx
Labels: 🦁 채빈, 🔨 Refactor

#117 fix/#116/스탬프 적립 페이지 params 사용
  src/components/CafeInfo/CafeDetail.jsx
  src/components/Home/CafeCarousel.jsx
  src/components/common/CafeListCard.jsx
  src/components/getStamp/StampAccess.jsx
  src/router.jsx
Labels: 🦁 채빈, 🔨 Refactor

#119 feat/#118/지도 검색 기능 구현
  package-lock.json
  package.json
  src/components/Map/KakaoMap.jsx
  src/components/Map/Map.jsx
  src/components/Map/SearchBox.jsx
  src/components/getStamp/QrVer2.jsx
  src/index.css
  src/router.jsx
Labels: 🦁 승채, ✨ Feature

#134 style/#132/StampAccess 컴포넌트 스타일 수정
  src/components/getStamp/StampAccess.Styled.js
Labels: 🦁 채빈, 🎨 Design

#149 Style/#148/카페 캐러셀 로딩중 텍스트 폰트 설정
  src/components/Home/CafeCarousel.jsx
  src/components/Home/styled.js
Labels: 🦁 채빈, 🎨 Design

#151 Docs/#150/폴더 구조 정리
  src/App.jsx
  src/components/Map/CafeSprout.jsx
  src/pages/CafeDetail.jsx
  src/pages/CafeList.jsx
  src/pages/GetStamp.jsx
  src/pages/Login.jsx
  src/pages/Map.jsx
  src/pages/OnBoarding.jsx
  src/pages/QrScan.jsx
  src/pages/SignUp.jsx
  src/pages/Splash.jsx
  src/pages/StampAccess.jsx
  src/router.jsx
Labels: 🦁 승채, 📃 Docs

#155 Chore/#153/주석 처리 코드 지우기
  src/pages/StampAccess.jsx
Labels: 📃 Docs
