Repository Likelion-at-SMWU-13th/Tumbloom-FE, pull requests merged in 2025-09, with the labels that each got.

#157 Design/#156/모바일 레이아웃 조정
  src/App.jsx
  src/components/CafeList/CafeList.Styled.js
  src/components/Coupon/styled.js
  src/components/Home/styled.js
  src/components/MyPage/styled.js
  src/components/Preference/styled.js
  src/components/common/Footer.Styled.js
  src/components/common/Header.Styled.js
  src/index.css
  src/pages/MyPage.jsx
Labels: 🦁 채빈, 🎨 Design

#159 Design/#158/온보딩 및 홈화면, 마이페이지 너비 조정
  src/components/Coupon/CouponChange.jsx
  src/components/Coupon/styled.js
  src/components/Home/styled.js
  src/components/MyPage/styled.js
  src/components/common/NoticeModal.Styled.js
  src/components/common/PwdInputField.Styled.js
  src/components/getStamp/GetStamp.Styled.js
  src/components/getStamp/StampAccess.Styled.js
  src/components/onboarding/Splash.Styled.js
  src/pages/MyPage.jsx
  src/pages/OnBoarding.jsx
Labels: 🦁 채빈, 🎨 Design

#162 161 chore 스타일 컴포넌트 파일 분리
  src/components/CafeInfo/CafeInfo.Styled.js
  src/components/CafeInfo/CafeInfoBox.jsx
  src/components/CafeInfo/MenuBox.jsx
  src/components/Map/KakaoMap.jsx
  src/components/Map/Map.Styled.js
  src/components/Map/MapBtn.jsx
  src/components/Map/MapCafeCard.jsx
  src/components/Map/SearchBox.jsx
Labels: 🦁 승채, 🎨 Design, 🔨 Refactor

#168 Feat/#164/Refresh Token 기반 자동 로그인 구현
  src/apis/api.js
  src/pages/Login.jsx
Labels: 🦁 승채, 📬 API, 🔨 Refactor

#176 Feat/#166/로그아웃 기능 구현
  src/components/MyPage/ProfileInfo.jsx
  src/components/MyPage/styled.js
Labels: 🦁 승채, ✨ Feature, 📬 API

#185 Chore/#174/큐알코드 페이지 주석 추가
  src/pages/QrScan.jsx
Labels: 🦁 승채, 🔨 Refactor

#186 Design/#178/컴포넌트 추가 너비 조정
  src/components/CafeInfo/CafeInfo.Styled.js
  src/components/FavoriteCafeList/styled.js
  src/components/Map/Map.Styled.js
  src/components/getStamp/GetStamp.Styled.js
Labels: 🦁 채빈, 🎨 Design
